// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package models_user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	Model
*/
package models_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Model struct {
	UserId            string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Username          string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Email             string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Password          string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	DatetimeCreatedAt string `protobuf:"bytes,6,opt,name=datetime_created_at,json=datetimeCreatedAt" json:"datetime_created_at,omitempty"`
	DatetimeUpdatedAt string `protobuf:"bytes,7,opt,name=datetime_updated_at,json=datetimeUpdatedAt" json:"datetime_updated_at,omitempty"`
}

func (m *Model) Reset()                    { *m = Model{} }
func (m *Model) String() string            { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()               {}
func (*Model) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Model) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Model) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Model) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Model) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Model) GetDatetimeCreatedAt() string {
	if m != nil {
		return m.DatetimeCreatedAt
	}
	return ""
}

func (m *Model) GetDatetimeUpdatedAt() string {
	if m != nil {
		return m.DatetimeUpdatedAt
	}
	return ""
}

type Model_Error struct {
	Msg  string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
}

func (m *Model_Error) Reset()                    { *m = Model_Error{} }
func (m *Model_Error) String() string            { return proto.CompactTextString(m) }
func (*Model_Error) ProtoMessage()               {}
func (*Model_Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Model_Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Model_Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*Model)(nil), "models.user.Model")
	proto.RegisterType((*Model_Error)(nil), "models.user.Model.Error")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0x40, 0x71, 0x6d, 0xd9, 0xed, 0x75, 0x69, 0xaf, 0x85, 0x0a, 0x4f, 0xa5, 0x53, 0x97, 0x7a,
	0xe9, 0x17, 0x98, 0xd2, 0x21, 0x43, 0x96, 0x40, 0x66, 0xa3, 0xf8, 0x8e, 0x60, 0xb0, 0x22, 0x23,
	0xc9, 0xe4, 0xeb, 0x03, 0x41, 0x52, 0x1c, 0xf0, 0x76, 0xef, 0xde, 0xbb, 0x41, 0x02, 0x98, 0x1d,
	0xdb, 0x66, 0xb2, 0xc6, 0x1b, 0x7c, 0xd6, 0x86, 0x78, 0x74, 0x4d, 0x58, 0x7d, 0x5d, 0x32, 0x10,
	0xdb, 0xc0, 0xf8, 0x01, 0x55, 0xd8, 0x74, 0x03, 0xc9, 0x87, 0xcf, 0xec, 0xfb, 0x69, 0x57, 0x06,
	0xdc, 0x10, 0xd6, 0xf0, 0x18, 0xa6, 0x93, 0xd2, 0x2c, 0xf3, 0x68, 0xee, 0x8c, 0xef, 0x20, 0x58,
	0xab, 0x61, 0x94, 0x45, 0x14, 0x09, 0xc2, 0xc5, 0xa4, 0x9c, 0x3b, 0x1b, 0x4b, 0x52, 0xa4, 0x8b,
	0x85, 0xb1, 0x81, 0x37, 0x52, 0x9e, 0xfd, 0xa0, 0xb9, 0xeb, 0x2d, 0x2b, 0xcf, 0xd4, 0x29, 0x2f,
	0xcb, 0x98, 0xbd, 0x2e, 0xea, 0x2f, 0x99, 0xd6, 0xaf, 0xfa, 0x79, 0xa2, 0xa5, 0xaf, 0xd6, 0xfd,
	0x3e, 0x99, 0xd6, 0xd7, 0x3f, 0x20, 0xfe, 0xad, 0x35, 0x16, 0x5f, 0x20, 0xd7, 0xee, 0x28, 0xb3,
	0x18, 0x86, 0x11, 0x11, 0x8a, 0xde, 0x10, 0xdf, 0x9e, 0x17, 0xe7, 0x43, 0x19, 0xff, 0xe4, 0xf7,
	0x1a, 0x00, 0x00, 0xff, 0xff, 0x12, 0xc7, 0xdc, 0x33, 0x21, 0x01, 0x00, 0x00,
}
